<?php

/**
 * Implementation of hook_install().
 */
function ca_external_polls_install() {
  variable_set('ca_external_polls_list_template', 'ca_external_polls_list_template_one');
  variable_set('ca_external_polls_node_template', 'ca_external_polls_node_template_one');
}

/**
 * Implementation of hook_uninstall().
 */
function ca_external_polls_uninstall() {
  variable_del('ca_external_polls_list_template');
  variable_del('ca_external_polls_node_template');
}
